# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180214_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link de facebook'),
        ),
    ]
