# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180227_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='discount',
        ),
    ]
