# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20180228_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='discountnew',
            new_name='discount',
        ),
    ]
