# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20180207_1707'),
        ('restaurant', '0009_auto_20180228_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdiscount',
            old_name='discountnew',
            new_name='discount',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantdiscount',
            unique_together=set([('restaurant', 'discount')]),
        ),
    ]
