# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20180228_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(default='', max_length=300, verbose_name='Link de facebook'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(default='', max_length=100, verbose_name='Whatsapp (Agregar "+51" si es de Perú)'),
        ),
    ]
