# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20180328_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdiscount',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
