# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurantdiscount_is_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdiscount',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='¿Está disponible?'),
        ),
    ]
