# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20180403_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Link de facebook'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Whatsapp (Agregar "+51" si es de Perú)'),
        ),
    ]
