# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20180411_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de prioridad'),
        ),
    ]
