# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='descrip',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripcion'),
        ),
    ]
