# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20180130_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='terms_condition',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Terminos y condiciones'),
        ),
    ]
