# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20180201_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='discount.Card', verbose_name='Tarjeta'),
        ),
    ]
