# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20180201_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='terms_condition',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Terminos y condiciones'),
        ),
    ]
