# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20180207_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
