# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_discount_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
