# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20180321_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='¿Está disponible?'),
        ),
    ]
