# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_gmail',
            field=models.BooleanField(default=False),
        ),
    ]
