# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-22 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180214_1103'),
        ('account', '0003_user_is_admin_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admrestaurants', to='restaurant.Restaurant')),
            ],
            options={
                'verbose_name': 'Admin y su restaurante',
                'verbose_name_plural': 'Super Admin y sus restaurantes',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Razón social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=' ', max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(default=' ', verbose_name='Comentarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ruc',
            field=models.CharField(default=' ', max_length=20, verbose_name='RUC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradminrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admrestaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, related_name='admrestaurants', through='account.UserAdminRestaurant', to='restaurant.Restaurant', verbose_name='Mis restaurantes'),
        ),
        migrations.AlterUniqueTogether(
            name='useradminrestaurant',
            unique_together=set([('user', 'restaurant')]),
        ),
    ]
