# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminrestaurant',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='¿Desea aceptar al nuevo usuario?'),
        ),
    ]
