# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-06 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useradminrestaurant_is_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradminrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admrestaurants', to='restaurant.Restaurant', verbose_name='Nombre de local'),
        ),
        migrations.AlterField(
            model_name='useradminrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admrestaurants', to=settings.AUTH_USER_MODEL, verbose_name='Email y nombre completo'),
        ),
    ]
