# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-06 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180306_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradminrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admrestaurants', to=settings.AUTH_USER_MODEL, verbose_name='Email - nombre completo'),
        ),
    ]
