# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180306_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminrestaurant',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
