# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_useradminrestaurant_send_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradminrestaurant',
            name='send_mail',
        ),
    ]
