# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_useradminrestaurant_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestaurant',
            name='is_color',
            field=models.BooleanField(default=False),
        ),
    ]
